## FPA

This class represents standard Cuckoo Search based on the explanation in the [\[book\]](https://doi.org/10.1016/B978-0-12-416743-8.00009-9) Nature-Inspired Optimization Algorithms by Xin-She Yang and his implementation of standard Cuckoo Search in Matlab on [\[mathworks\]](https://www.mathworks.com/matlabcentral/fileexchange/29809-cuckoo-search-cs-algorithm). The implementation is slightly different to the flow of the algorithm described in the book. The figures below describe the pseudocode of the algorithm from the book, and the flow of the implementation. The GRW stands for Global Random Walk by Levy Flight, and the LRW stands for Local Random Walk.

1) **Initial Population:**: A starting population is sampled in the beginning. In this framework, this can be either a [Sampling](../operators/sampling.ipynb) object, which defines different initial sampling strategies, or `Population` where the `X` and `F` values are set, or a simple NumPy array (pop_size x n_var).

2) **Evaluation:** It is executed using the problem defined to be solved.

3) **Survival:** The survival mechanism used is by default the survival of the fittest for the Elitism.

4) **Global Random Walk:** The global random walks use a step size that is generated based on Levy Flight Distribution. Every dimension will have its own randomly generated step size on every operation. The Global Random Walk can be done following the book which to randomly choose solution $x_{i}$ which will be modified by Global Random Walk resulting in $x'_i$ and replace a randomly chosen solution $x_{j}$, if $x'_{i}$ is better than $x_{j}$. However for simplicity sake, as also been done in the matlab implementation, $x'_{i}$ will be compared to $x_{i}, \forall i$ in every iteration. 

5) **Local Random Walk:** After the Global Random Walk has been done, including the replacement after improvement, every nest $x_i$ has a $p_a$ probability to create new solution via Local Ranom Walk $x'_i = x_i + \alpha_0*(x_j-x_k)$ with $x_j$ and $x_k$ are two different randomly selected nest. Afterwards, combine the old nests with the new generated nests via Local Random Walks. The size of the combined nests will be pop_size $\leq$ combined_pop_size $\leq 2$pop_size. Survival mechanism thus will be used to select a number of pop_size best nests.



<div style="display: block;margin-left: auto;margin-right: auto;width: 60%;">
![cs_pseudocode](../resources/images/cuckoo_search_pseudocode.png)
</div>

<div style="display: block;margin-left: auto;margin-right: auto;width: 60%;">
![cs_flow](../resources/images/cuckoo_search_flow.png)
</div>

### Example

In [1]:
from pymoo.algorithms.moead_fpa import MOEAD_ALFPA
from pymoo.factory import get_problem, get_visualization, get_reference_directions
from pymoo.optimize import minimize
from pymoo.visualization.scatter import Scatter
from pymoo.decomposition.tchebicheff import Tchebicheff

problem = get_problem("dtlz1")
n_obj = 3
ref_dirs = get_reference_directions("das-dennis", n_obj, n_partitions=15)
algorithm = MOEAD_ALFPA(ref_dirs, decomposition=Tchebicheff())

res = minimize(problem, algorithm, ('n_eval', 25000), verbose=False)

if n_obj == 2:
    plot = Scatter()
    plot.add(problem.pareto_front(), plot_type="line", color="black", alpha=0.7)
    plot.add(res.F, color="red")
    plot.show()
else:
    plot = Scatter().add(res.F)
    plot.show()

[  4  13  15  25  26  30  31  37  39  44  47  53  57  64  70  75  92  93
 116 130 132 133 135]
[  3   4   5   6   7   8   9  10  11  12  13  14  19  20  21  22  23  24
  25  26  27  28  29  34  35  36  37  38  39  40  41  42  43  48  49  50
  51  52  53  54  56  61  62  63  64  65  66  68  72  73  74  75  76  77
  78  79  83  84  85  86  87  88  89  94  95  96  97  98  99 100 101 102
 103 104 105 106 108 109 110 111 112 113 115 116 117 118 119 121 122 123
 124]


/home/gemilang/python/python-mop/src/mypymoo/pymoo/algorithms/moead_fpa.py:200: RuntimeWarning: divide by zero encountered in true_divide
  G = (FV - off_FV)/FV
/home/gemilang/python/python-mop/src/mypymoo/pymoo/algorithms/moead_fpa.py:200: RuntimeWarning: invalid value encountered in true_divide
  G = (FV - off_FV)/FV
/home/gemilang/python/python-mop/src/mypymoo/pymoo/operators/mutation/polynomial_mutation.py:47: RuntimeWarning: invalid value encountered in power
  d = np.power(val, mut_pow) - 1.0


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  31  32  33  36  37  38  39
  40  41  42  43  45  46  47  48  49  50  51  52  53  56  58  59  60  61
  62  70  71  72  73  81  82  83  84  85  86  91  92  93  94  95  96  97
  98  99 100 101 102 103 104 105 106 108 109 110 111 112 113 115 116 117
 118 119 121 122 123 124 126 127 128 130 131]
[  0   1   2   3  12  13  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  31  32  33  34  35  36  37  38  39  40  41  42  43  45  46  47
  48  49  50  51  52  54  55  56  58  59  60  61  62  63  64  65  66  67
  68  70  71  72  73  74  75  76  77  78  79  81  82  83  84  85  86  87
  88  89  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106
 108 109 110 111 112 113 115 116 117 118 119 121 122 123 124 126 127 128
 130 131 133]
[ 12  13  17  18  19  20  21  22  32  33  34  35  36  37  38  39  40  46
  47  48  49  50  51  52  53  54  55  59  60  61  62  63  64  65

/home/gemilang/python/python-mop/src/mypymoo/pymoo/operators/mutation/polynomial_mutation.py:52: RuntimeWarning: invalid value encountered in power
  d = 1.0 - (np.power(val, mut_pow))
/home/gemilang/python/python-mop/src/mypymoo/pymoo/decomposition/tchebicheff.py:27: RuntimeWarning: invalid value encountered in multiply
  v = anp.abs(F - self.utopian_point) * weights


[ 12  13  17  18  19  20  21  22  23  24  25  26  27  28  29  32  34  35
  36  37  38  39  40  41  42  43  46  47  48  49  50  51  52  53  54  55
  56  59  62  63  64  65  66  67  68  70  74  75  76  77  78  79  81  83
  85  86  87  88  89  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 108 109 110 111 112 113 115 116 117 118 119 121 122 123 124]
[  1   2  17  18  19  20  21  22  23  24  29  32  33  34  35  36  37  38
  39  46  47  48  49  50  51  52  59  60  61  62  63  64  65  70  71  72
  73  74  75  76  81  82  83  84  85  87  88  91  92  93  94  95  96  97
  99 100 101 102 103 105 106 108 109 110 111 112 113 115 116 117 118 119
 121 122 123 124 127 128 131]
[  1   2  17  18  19  20  21  22  23  24  25  26  27  28  29  32  33  34
  35  36  37  38  39  40  41  42  43  46  47  48  49  50  51  52  53  54
  55  56  59  60  61  62  63  64  65  66  67  68  70  71  72  73  74  75
  76  77  78  79  81  82  83  84  85  86  87  88  89  91  92  93  94  95
  96  97  98  99 100

/home/gemilang/python/python-mop/src/mypymoo/pymoo/algorithms/moead_fpa.py:147: RuntimeWarning: invalid value encountered in true_divide
  FRR = np.dot(current_mask, self.op_rewards)/tot_rewards


[  1   2  17  19  20  21  22  23  24  25  26  27  28  29  34  35  36  37
  38  39  40  41  42  43  47  48  49  50  51  52  53  54  55  56  60  61
  62  63  65  66  67  68  70  73  74  76  77  78  79  81  86  87  88  89
  91  95  96  97  98  99 100 102 103 104 105 106 108 109 110 111 112 113
 115 116 117 119 121 122 124 127 128 131]
[  1   2  17  18  19  20  21  22  23  24  25  26  27  28  29  32  33  34
  35  36  37  38  39  40  41  42  43  46  47  48  49  50  51  52  53  54
  55  56  59  60  61  62  63  64  65  66  67  68  70  71  72  75  76  77
  78  79  81  85  86  87  88  89  91  94  95  96  97  98  99 100 102 103
 104 105 106 108 110 111 112 113 115 116 117 118 119 121 122 124 127 128
 131]
[  1   2  17  18  19  20  21  22  23  24  25  26  27  28  29  32  33  34
  35  36  37  38  39  40  41  42  43  46  47  48  49  50  51  52  53  54
  55  56  59  60  61  62  63  64  65  66  67  68  70  71  72  73  74  75
  76  77  78  79  81  82  83  84  85  86  87  88  89  91  92  93  94  95
  9

KeyboardInterrupt: 

In [4]:
print(res.exec_time)

16.23816990852356


In [22]:
import numpy as np
A = np.random.randint(5, size=10)
idx = np.arange(5)
idx = np.tile(idx, (len(A),1)).T
print(A)
mask = (A==idx).astype(dtype='float')
print(np.sum(mask, axis=1))
print(np.dot(mask, A.T))

[4 3 2 0 4 0 3 3 4 3]
[2. 0. 1. 4. 3.]
[ 0.  0.  2. 12. 12.]


### API